---
# tasks file for ansible-gimp-dependencies
#lineinfile does not support global option; see https://github.com/ansible/ansible/issues/5535
- name: "Ensure sources.list is Debian Testing"
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: '^(deb.*)jessie(.*main)$'
    line: '\1testing\2'
    backrefs: yes
  register: result
  until: result.changed == false
  retries: 5
  delay: 0
  #shell: "sed -ri -- 's/^(deb.*)jessie(.*main)$/\\1testing\\2/' /etc/apt/sources.list"
- name: "Perform dist-upgrade"
  apt:
    update_cache: yes
    upgrade: dist
  register: result
  until: result|success
  retries: 5
  delay: 3
- name: "Update apt cache"
  apt:
    update_cache: yes
- name: Install GIMP dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ babl_deps + gegl_deps + libmypaint_deps + gimp_deps }}"
  register: result
  until: result|success
  retries: 5
  delay: 3
